sensor_msgs/JointState external_joint_measurements
# optional: these joint states are the original joint state during the external measurement
# if not provided, the current joint states from the transmission interface will be used
sensor_msgs/JointState original_joint_state
---
float64[] adjusted_offsets
bool success
string message
